### ISSUE TITLE
macOS Monterey all settings greyed out

### ISSUE THREAD

**Issue by affrae** [Itaybre/CameraController#15] opened 2021-08-13 00:54 UTC
**Describe the bug**

in macOS Monterey all settings greyed out

**To Reproduce**
1. Launch app
2. Choose your camera

**Expected behavior**
Able to set settings for the camera

**Screenshots**

**_Note: camera does show up I have just blacked out the camera image._**

![Screen Shot 2021-08-13 at 10 49 11 am](https://user-images.githubusercontent.com/745341/129288014-31c2daec-b0aa-49b3-9975-436deadc4ea1.png)
![Screen Shot 2021-08-13 at 10 49 14 am](https://user-images.githubusercontent.com/745341/129288019-ec628b2f-f82c-40d3-ba90-a93505ae47da.png)
![Screen Shot 2021-08-13 at 10 49 18 am](https://user-images.githubusercontent.com/745341/129288023-0a91ac4f-fab0-45b7-a82d-821eea785fc7.png)

**Desktop (please complete the following information):**
 - Version: 1.2.1(4) from https://github.com/Itaybre/CameraController/files/6825344/CameraController.zip
 - Camera: Logitech Brio
 - macOS: 12.0 Monterey Public Beta 5

**Additional context**
Hi! I know it is a beta OS but opening here for reference, not expecting an immediate fix :)

**Comment by Itaybre** [comment] 2021-08-20 14:13
@affrae I would like to see the USB Descriptor for this camera.
Can you share it using [this](https://github.com/Itaybre/CameraController/issues/11#issuecomment-880016985) method?

**Comment by affrae** [comment] 2021-08-22 23:22
@Itaybre Here you go - hope this helps!

[USB Bus Probe.txt](https://github.com/Itaybre/CameraController/files/7028315/USB.Bus.Probe.txt)

**Comment by Itaybre** [comment] 2021-08-24 03:34
The descriptor seems to be fine, I will be testing this on a VM this weekend and already found a provider for the webcam locally in case the issue is with the camera and not Monterey

**Comment by affrae** [comment] 2021-08-24 03:34
Wow - thank you!!

**Comment by enquora** [comment] 2021-08-24 05:34
> The descriptor seems to be fine, I will be testing this on a VM this weekend and already found a provider for the webcam locally in case the issue is with the camera and not Monterey

The problem occurs with a Microsoft Lifecam also - it’s Monterey rather than any specific camera.

**Comment by tfpbatelaan** [comment] 2021-08-25 09:04
Hey there, this also occurs on Big Sur on my 15-inch mid-2015 Macbook Pro. It doesn't even work with the built-in!

**Comment by Itaybre** [comment] 2021-08-25 13:01
> Hey there, this also occurs on Big Sur on my 15-inch mid-2015 Macbook Pro. It doesn't even work with the built-in! 

That's expected behavior with built-in camera, apple doesn't allow low level communication with it

**Comment by bkboy21** [comment] 2021-08-31 18:50
hey , im using a mac mini and this webcam : 
https://www.amazon.com/dp/B08DXSG5QR/ref=cm_sw_r_apan_glt_fabc_XKFH6SSFZXRYQSP0XB7P?_encoding=UTF8&psc=1

all settings work but pan\zoom\tilt wont work . anything we can do about that ?
thank you for your contribution !!!!

**Comment by affrae** [comment] 2021-08-31 21:08
I should point out that LogiTune is not working either, so we may need to be patient here as it could be an underlying Beta issue, or require some rework generally.

**Comment by apobst83** [comment] 2021-09-02 11:19
+1 on the greyed out sliders in monterey. I am using a Dell Ultrasharp 4k Webcam.

**Comment by jrykner** [comment] 2021-09-13 20:32
+1 with latest Mac OS12 Beta 6, greyed out sliders, with logitech c922 webcam, it does recognize and preview, on Mac M1 but all options are greyed out

**Comment by mattiasstahre** [comment] 2021-09-22 14:25
+1 All settings are greyed out. I'm on Beta 7

**Comment by don-sch** [comment] 2021-10-05 19:51
+1 Any updates on this? I'm on beta 12. No worries if you're still figuring this one out.

**Comment by Itaybre** [comment] 2021-10-31 21:49
Fix merged, working on another fix and will upload a new build

**Closed by Itaybre** 2021-10-31 21:49 UTC
Labels: bug, Monterey

**Comment by affrae** [comment] 2021-10-31 21:55
Thank you, sir! Without me pitching the feature, you should look into sponsorship 😈

**Comment by olsw** [comment] 2021-11-01 11:13
Latest build failed so can't get this version, could you take a look please

**Comment by affrae** [comment] 2021-11-01 19:54
Confirmed [1.3.1 Release](https://github.com/Itaybre/CameraController/releases/tag/1.3.1) binary working for me on Monterey.

**Comment by Itaybre** [comment] 2021-11-01 19:57
@olsw you can download build 1.3.1 from the release now


> Thank you, sir! Without me pitching the feature, you should look into sponsorship 😈

Unfortunately Github Sponsors is not available on my country and I did setup a Ko-fi site, but still haven't been able to give it some love.
I may add the sponsor link once I finish v2.0 with menu bar configuration

**Comment by affrae** [comment] 2021-11-01 20:18
> Unfortunately Github Sponsors is not available on my country 

Oh manh I forgot about that, sorry.

**Comment by 4ndv** [comment] 2022-01-03 17:34
Sadly, but for me it's still the same. Tested on 12.0.1, then updated to 12.1 but all the settings is still greyed out :(

**Comment by affrae** [comment] 2022-01-03 22:58
@4ndv what camera?

**Comment by bobbynj81** [comment] 2022-01-10 19:30
@affrae Everything is grayed out for me as well on Mac Monterey, M1 Mini with a Logitech Brio.

**Comment by affrae** [comment] 2022-01-10 20:34
Hi folks I'm just another user like y'all. I opened the issue here and since then the issue has been resolved for me. I can't help much here. 

@Itaybre do yo want folks posting on this issue, or close this one off and get folks to open a new one?

**Comment by rinogo** [comment] 2023-03-30 18:44
Same issue, this time with an "HD Webcam eMeet C980 Pro".

**Comment by vogithub1** [comment] 2024-02-29 23:15
Same issue - Macbook Air 13 2015 FaceTime HD Camera Monterey 12 3 1

**Comment by SoftwareApe** [comment] 2025-05-06 14:38
Same issue with OBSBot Meet 2.

**Comment by maxboisvert** [comment] 2026-01-07 17:30
I may have found a workaround / tmp fix:

1. Stop the CameraController app
2. Go in Settings / Security & Privacy / Privacy (tab)
3. Select Camera (in left pane)
4. Uncheck and re-check CameraController
